name: llava-more
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=4.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=4.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - cffi=1.16.0
  - comm=0.2.1
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.6.37
  - cuda-runtime=12.1.0
  - cuda-version=12.6
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - ffmpeg=4.3
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - intel-openmp=2023.1.0
  - ipykernel=6.28.0
  - jedi=0.19.1
  - jpeg=9e
  - json5=0.9.6
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.11.0.15
  - libcurand=10.3.7.37
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - notebook-shim=0.2.3
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.14
  - overrides=7.4.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pip=24.2
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.10.14
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - pytorch=2.3.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - readline=8.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - send2trash=1.8.2
  - setuptools=72.1.0
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - sympy=1.12
  - tbb=2021.8.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.14
  - tomli=2.0.1
  - torchaudio=2.3.1
  - torchvision=0.18.1
  - typing_extensions=4.11.0
  - tzdata=2024a
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - accelerate==0.33.0
      - aiohttp==3.9.5
      - altair==5.3.0
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - attrs==23.2.0
      - autofaiss==2.17.0
      - backcall==0.2.0
      - blinker==1.7.0
      - braceexpand==0.1.7
      - cairocffi==1.6.1
      - cairosvg==2.7.1
      - certifi==2024.2.2
      - cfgv==3.4.0
      - chardet==5.2.0
      - charset-normalizer==2.1.1
      - click==8.1.7
      - cloudpathlib==0.16.0
      - cmake==3.25.0
      - colorama==0.4.6
      - confection==0.1.4
      - contexttimer==0.3.3
      - contourpy==1.1.1
      - cssselect2==0.7.0
      - dataproperty==1.0.1
      - datasets==2.19.1
      - decord==0.6.0
      - distlib==0.3.8
      - einops==0.7.0
      - embedding-reader==1.7.0
      - en-core-web-lg==3.7.1
      - evaluate==0.4.2
      - fairscale==0.4.4
      - faiss-cpu==1.7.4
      - filelock==3.13.3
      - fire==0.5.0
      - flash-attn==2.6.2
      - fonttools==4.50.0
      - fsspec==2024.2.0
      - ftfy==6.2.0
      - gitpython==3.1.42
      - hf-transfer==0.1.6
      - huggingface-hub==0.23.3
      - identify==2.5.35
      - idna==3.4
      - imageio==2.34.0
      - importlib-resources==6.4.0
      - iopath==0.1.10
      - ipython==8.12.3
      - jinja2==3.1.2
      - jsonschema==4.21.1
      - kaggle==1.6.8
      - langcodes==3.3.0
      - lazy-loader==0.3
      - lit==15.0.7
      - lxml==5.2.2
      - matplotlib==3.7.5
      - mbstrdecoder==1.1.3
      - natsort==8.4.0
      - networkx==3.0
      - nodeenv==1.8.0
      - numpy==1.24.1
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==8.7.0.84
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - omegaconf==2.3.0
      - opencv-python-headless==4.5.5.64
      - opendatasets==0.1.22
      - packaging==23.2
      - pandas==2.0.3
      - pathvalidate==3.2.0
      - pickleshare==0.7.5
      - pillow==10.2.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.2.0
      - plotly==5.20.0
      - portalocker==2.8.2
      - pre-commit==3.5.0
      - protobuf==4.25.3
      - psutil==5.9.8
      - pyarrow==15.0.0
      - pyarrow-hotfix==0.6
      - pycocoevalcap==1.2
      - pycocotools==2.0.7
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - pydeck==0.8.1b0
      - pygments==2.17.2
      - pynvml==11.5.0
      - pyparsing==3.1.2
      - pytablewriter==1.2.0
      - python-dateutil==2.8.2
      - python-magic==0.4.27
      - pywavelets==1.4.1
      - referencing==0.34.0
      - regex==2023.12.25
      - rpds-py==0.18.0
      - sacrebleu==2.4.2
      - safetensors==0.4.2
      - salesforce-lavis==1.0.2
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - sentencepiece==0.2.0
      - sentry-sdk==1.42.0
      - smart-open==6.4.0
      - spacy==3.7.4
      - sqlitedict==2.1.0
      - streamlit==1.32.2
      - tabledata==1.3.3
      - tabulate==0.9.0
      - tcolorpy==0.1.6
      - tenacity==8.2.3
      - thinc==8.2.3
      - tifffile==2023.7.10
      - timm==0.4.12
      - tokenizers==0.19.1
      - toml==0.10.2
      - toolz==0.12.1
      - tornado==6.4
      - tqdm==4.66.2
      - traitlets==5.14.2
      - transformers==4.44.2
      - triton==2.3.0
      - typepy==1.3.2
      - typer==0.9.4
      - typing-extensions==4.10.0
      - ujson==5.9.0
      - urllib3==1.26.13
      - virtualenv==20.25.1
      - wandb==0.16.4
      - wasabi==1.1.2
      - watchdog==4.0.0
      - weasel==0.3.4
      - webdataset==0.2.86
      - wget==3.2
      - xxhash==3.4.1
      - zipp==3.18.1
